### PR TITLE
allow option getNextValue

### PR DESCRIPTION
**Pull request by benib**
if getNextValue is a function, it gets called with the request as a parameter and should return a string that is appended to the url in the next parameter.

example:
```
server.auth.strategy('couchdb', 'couchdb-cookie', {
  couchdbUrl: process.env.COUCH_DB_URL,
  redirectTo: process.env.LOGIN_URL || '/login',
  appendNext: true,
  getNextValue: function(request) {
    return encodeURIComponent(request.url.path);
  }
});
```
If there are any questions or there is anything I can do to improve this, please let know.

### CODE REVIEW

**Comment by KlausTrainer** [comment]
Hi @benib!

Thanks, looks good :)

I'd just like to make sure that it is also documented. Could you please add a section to the README that explains what `getNextValue` does? I'd suggest inserting it after the `appendNext` section.

**Comment by benib** [comment]
@KlausTrainer sure, documentation is added with the latest commit.

**Comment by benib** [comment]
@KlausTrainer can or should I do something else to get this merged?

**Comment by KlausTrainer** [comment]
Thanks @benib!

And sorry for looking at it just now.

**Comment by benib** [comment]
Thanks a lot for 3.1.0!

**Pull request merged**
